# 🐼 Pandas Class 8 Assignment — Time Series

### Level: Easy → Intermediate

**Topics:** `pd.to_datetime()` • DateTime index • date filtering/slicing • `resample()` • rolling windows • expanding windows

**Instructions:** Do not load a CSV. Create the DataFrame in Q1 and use it throughout. Solve each question in the blank code cell and check the Expected Output.

In [ ]:
import pandas as pd

## Q1. Create a DataFrame named `sales`:

| Date | Product | Sales |
|---|---|---:|
| 2024-02-01 | Laptop | 50000 |
| 2024/02/03 | Mouse | 1200 |
| 05-02-2024 | Keyboard | 2500 |
| 2024-02-10 | Monitor | 15000 |
| 20240215 | Laptop | 52000 |
| 2024-02-18 | Mouse | 1400 |
| 20-02-2024 | Keyboard | 2800 |
| 2024-02-25 | Monitor | 16000 |
| 2024/02/27 | Laptop | 48000 |
| 2024-02-29 | Mouse | 1300 |

Expected Output: 10 rows × 3 columns.

In [ ]:
# Write your answer here
sales = pd.DataFrame({
    'date' : ["2024-02-01", "2024/02/03", "05-02-2024", "2024-02-10", "20240215", "2024-02-18", "20-02-2024", "2024-02-25", "2024/02/27", "2024-02-29"],
    'product' : ["Laptop", "Mouse", "Keyboard", "Monitor", "Laptop", "Mouse", "Keyboard", "Monitor", "Laptop", "Mouse"],
    'sales' : [50000, 1200, 2500, 15000, 52000, 1400, 2800, 16000, 48000, 1300]
})
sales

         date   product  sales
0  2024-02-01    Laptop  50000
1  2024/02/03     Mouse   1200
2  05-02-2024  Keyboard   2500
3  2024-02-10   Monitor  15000
4    20240215    Laptop  52000
5  2024-02-18     Mouse   1400
6  20-02-2024  Keyboard   2800
7  2024-02-25   Monitor  16000
8  2024/02/27    Laptop  48000
9  2024-02-29     Mouse   1300

## Q2. Convert `Date` to datetime using `pd.to_datetime()`.

Expected Output: Date has datetime dtype.

In [ ]:
# Write your answer here
sales['date'] = pd.to_datetime(sales['date'], format='mixed')

print(sales.dtypes)

date       datetime64[ns]
product            object
sales               int64
dtype: object

## Q3. Find the earliest and latest dates.

Expected Output: Minimum and maximum dates are displayed.

In [ ]:
# Write your answer here
earliest_date = sales['date'].min()
latest_date = sales['date'].max()

print("Earliest date:", earliest_date)
print("Latest date:", latest_date)

Earliest date: 2024-02-01 00:00:00
Latest date: 2024-05-02 00:00:00

## Q4. Filter records after `2024-02-10`.

Expected Output: Only records after February 10.

In [ ]:
# Write your answer here
filtered_sales = sales[sales['date'] > '2024-02-10']

print(filtered_sales)

        date   product  sales
2 2024-05-02  Keyboard   2500
4 2024-02-15    Laptop  52000
5 2024-02-18     Mouse   1400
6 2024-02-20  Keyboard   2800
7 2024-02-25   Monitor  16000
8 2024-02-27    Laptop  48000
9 2024-02-29     Mouse   1300

## Q5. Filter records between `2024-02-05` and `2024-02-20`.

Expected Output: Records in that date range.

In [ ]:
# Write your answer here
filtered_sales = sales[
    sales['date'].between('2024-02-05', '2024-02-20')
]

print(filtered_sales)

        date   product  sales
3 2024-02-10   Monitor  15000
4 2024-02-15    Laptop  52000
5 2024-02-18     Mouse   1400
6 2024-02-20  Keyboard   2800

## Q6. Set `Date` as the DataFrame index.

Expected Output: Date becomes a DateTimeIndex.

In [ ]:
# Write your answer here
sales['date'] = pd.to_datetime(sales['date'], format='mixed')

sales = sales.set_index('date')

print(sales)
print(type(sales.index))

             product  sales
date
2024-02-01    Laptop  50000
2024-02-03     Mouse   1200
2024-05-02  Keyboard   2500
2024-02-10   Monitor  15000
2024-02-15    Laptop  52000
2024-02-18     Mouse   1400
2024-02-20  Keyboard   2800
2024-02-25   Monitor  16000
2024-02-27    Laptop  48000
2024-02-29     Mouse   1300
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

## Q7. Using the DateTime index, select all February 2024 records.

Expected Output: All February records.

In [ ]:
# Write your answer here
feb_sales = sales.loc['2024-02']

print(feb_sales)

             product  sales
date
2024-02-01    Laptop  50000
2024-02-03     Mouse   1200
2024-02-10   Monitor  15000
2024-02-15    Laptop  52000
2024-02-18     Mouse   1400
2024-02-20  Keyboard   2800
2024-02-25   Monitor  16000
2024-02-27    Laptop  48000
2024-02-29     Mouse   1300

## Q8. Select records from `2024-02-10` to `2024-02-20` using date slicing.

Expected Output: Records in that range.

In [ ]:
# Write your answer here
sales = sales.sort_index()

sales.loc['2024-02-10':'2024-02-20']

             product  sales
date
2024-02-10   Monitor  15000
2024-02-15    Laptop  52000
2024-02-18     Mouse   1400
2024-02-20  Keyboard   2800

## Q9. Resample by week and calculate total Sales.

Expected Output: Weekly total Sales.

In [ ]:
# Write your answer here
weekly_sales = sales['sales'].resample('W').sum()

print(weekly_sales)

date
2024-02-04    51200
2024-02-11    15000
2024-02-18    53400
2024-02-25    18800
2024-03-03    49300
2024-03-10        0
2024-03-17        0
2024-03-24        0
2024-03-31        0
2024-04-07        0
2024-04-14        0
2024-04-21        0
2024-04-28        0
2024-05-05     2500
Freq: W-SUN, Name: sales, dtype: int64

## Q10. Resample by month and calculate total Sales.

Expected Output: One monthly total for February.

In [ ]:
# Write your answer here
monthly_sales = sales['sales'].resample('ME').sum()

print(monthly_sales)

date
2024-02-29    187700
2024-03-31         0
2024-04-30         0
2024-05-31      2500
Freq: ME, Name: sales, dtype: int64

## Q11. Resample by month and calculate average Sales.

Expected Output: One monthly average.

In [ ]:
# Write your answer here
monthly_avg_sales = sales['sales'].resample('ME').mean()

print(monthly_avg_sales)

date
2024-02-29    20855.555556
2024-03-31             NaN
2024-04-30             NaN
2024-05-31     2500.000000
Freq: ME, Name: sales, dtype: float64

## Q12. Resample by day and calculate total Sales.

Expected Output: Daily totals.

In [ ]:
# Write your answer here
daily_sales = sales['sales'].resample('D').sum()

print(daily_sales)

date
2024-02-01    50000
2024-02-02        0
2024-02-03     1200
2024-02-04        0
2024-02-05        0
              ...
2024-04-28        0
2024-04-29        0
2024-04-30        0
2024-05-01        0
2024-05-02     2500
Freq: D, Name: sales, Length: 92, dtype: int64

## Q13. Calculate a 3-observation rolling average of Sales using `rolling()`.

Expected Output: Rolling average series; initial values may be NaN.

In [ ]:
# Write your answer here
rolling_avg = sales['sales'].rolling(3).mean()

print(rolling_avg)

date
2024-02-01             NaN
2024-02-03             NaN
2024-02-10    22066.666667
2024-02-15    22733.333333
2024-02-18    22800.000000
2024-02-20    18733.333333
2024-02-25     6733.333333
2024-02-27    22266.666667
2024-02-29    21766.666667
2024-05-02    17266.666667
Name: sales, dtype: float64

## Q14. Calculate a 3-observation rolling sum of Sales.

Expected Output: Rolling 3-observation totals.

In [ ]:
# Write your answer here
rolling_sum = sales['sales'].rolling(3).sum()

print(rolling_sum)

date
2024-02-01        NaN
2024-02-03        NaN
2024-02-10    66200.0
2024-02-15    68200.0
2024-02-18    68400.0
2024-02-20    56200.0
2024-02-25    20200.0
2024-02-27    66800.0
2024-02-29    65300.0
2024-05-02    51800.0
Name: sales, dtype: float64

## Q15. Calculate the expanding average using `expanding().mean()`.

Expected Output: Cumulative average after each observation.

In [ ]:
# Write your answer here
expanding_avg = sales['sales'].expanding().mean()

print(expanding_avg)

date
2024-02-01    50000.000000
2024-02-03    25600.000000
2024-02-10    22066.666667
2024-02-15    29550.000000
2024-02-18    23920.000000
2024-02-20    20400.000000
2024-02-25    19771.428571
2024-02-27    23300.000000
2024-02-29    20855.555556
2024-05-02    19020.000000
Name: sales, dtype: float64

## Q16. Calculate the expanding sum using `expanding().sum()`.

Expected Output: Cumulative Sales total.

In [ ]:
# Write your answer here
expanding_sum = sales['sales'].expanding().sum()

print(expanding_sum)

date
2024-02-01     50000.0
2024-02-03     51200.0
2024-02-10     66200.0
2024-02-15    118200.0
2024-02-18    119600.0
2024-02-20    122400.0
2024-02-25    138400.0
2024-02-27    186400.0
2024-02-29    187700.0
2024-05-02    190200.0
Name: sales, dtype: float64

## Q17. Find the week with the highest total Sales after weekly resampling.

Expected Output: One week and its total Sales.

In [ ]:
# Write your answer here
weekly_sales = sales['sales'].resample('W').sum()

highest_week = weekly_sales.idxmax()
highest_sales = weekly_sales.max()

print("Week:", highest_week)
print("Total Sales:", highest_sales)

Week: 2024-02-18 00:00:00
Total Sales: 53400

## Q18. Create a monthly summary with both total Sales and average Sales.

Expected Output: One row for February with two statistics.

In [ ]:
# Write your answer here
monthly_summary = sales['sales'].resample('ME').agg(['sum', 'mean'])

print(monthly_summary)

               sum          mean
date
2024-02-29  187700  20855.555556
2024-03-31       0           NaN
2024-04-30       0           NaN
2024-05-31    2500   2500.000000

## Q19. Find the date on which the highest individual Sales value occurred.

Expected Output: One date and its Sales value.

In [ ]:
# Write your answer here
highest_date = sales['sales'].idxmax()
highest_sales = sales['sales'].max()

print("Date:", highest_date)
print("Sales:", highest_sales)

Date: 2024-02-15 00:00:00
Sales: 52000

# ⭐ Bonus Challenge

Create your own 15-day sales dataset with `Date`, `Product`, and `Sales`.

Then:
- Convert Date to datetime.
- Set Date as index.
- Find weekly Sales.
- Calculate a 3-day rolling average.
- Calculate an expanding maximum.
- Find the best-performing week.

**Goal:** Perform the complete time-series workflow on your own dataset.

In [ ]:
# Bonus solution
import pandas as pd

# Create dataset
sales = pd.DataFrame({
    'Date': [
        '2024-03-01', '2024-03-02', '2024-03-03',
        '2024-03-04', '2024-03-05', '2024-03-06',
        '2024-03-07', '2024-03-08', '2024-03-09',
        '2024-03-10', '2024-03-11', '2024-03-12',
        '2024-03-13', '2024-03-14', '2024-03-15'
    ],
    'Product': [
        'Laptop', 'Mouse', 'Keyboard',
        'Monitor', 'Laptop', 'Mouse',
        'Keyboard', 'Monitor', 'Laptop',
        'Mouse', 'Keyboard', 'Monitor',
        'Laptop', 'Mouse', 'Monitor'
    ],
    'Sales': [
        45000, 1200, 2500,
        14000, 50000, 1500,
        2800, 16000, 48000,
        1300, 3000, 15500,
        52000, 1400, 17000
    ]
})

# Convert Date to datetime
sales['Date'] = pd.to_datetime(sales['Date'])

# Set Date as index
sales = sales.set_index('Date').sort_index()

# Weekly Sales
weekly_sales = sales['Sales'].resample('W').sum()

# 3-day rolling average
rolling_avg = sales['Sales'].rolling(3).mean()

# Expanding maximum
expanding_max = sales['Sales'].expanding().max()

# Best-performing week
best_week = weekly_sales.idxmax()
best_week_sales = weekly_sales.max()

print("Weekly Sales:")
print(weekly_sales)

print("\n3-Day Rolling Average:")
print(rolling_avg)

print("\nExpanding Maximum:")
print(expanding_max)

print("\nBest-performing Week:")
print("Week:", best_week)
print("Sales:", best_week_sales)

Weekly Sales:
Date
2024-03-03     48700
2024-03-10    133600
2024-03-17     88900
Freq: W-SUN, Name: Sales, dtype: int64

3-Day Rolling Average:
Date
2024-03-01             NaN
2024-03-02             NaN
2024-03-03    16233.333333
2024-03-04     5900.000000
2024-03-05    22166.666667
2024-03-06    21833.333333
2024-03-07    18100.000000
2024-03-08     6766.666667
2024-03-09    22266.666667
2024-03-10    21766.666667
2024-03-11    17433.333333
2024-03-12     6600.000000
2024-03-13    23500.000000
2024-03-14    22966.666667
2024-03-15    23466.666667
Name: Sales, dtype: float64

Expanding Maximum:
Date
2024-03-01    45000.0
2024-03-02    45000.0
2024-03-03    45000.0
2024-03-04    45000.0
2024-03-05    50000.0
2024-03-06    50000.0
2024-03-07    50000.0
2024-03-08    50000.0
2024-03-09    50000.0
2024-03-10    50000.0
2024-03-11    50000.0
2024-03-12    50000.0
2024-03-13    52000.0
2024-03-14    52000.0
2024-03-15    52000.0
Name: Sales, dtype: float64

Best-performing Week:
Week: 2024-03-10 00:00:00
Sales: 133600