# Pandas Assignment (Q1–Q15)

Fill the code in the empty code cells.

In [ ]:
import pandas as pd
import numpy as np

## Q1. Create the **Below** DataFrame.

Expected Output:
```
    Name   Age  Marks     City
0   Aman  20.0   85.0    Delhi
1   Neha   NaN   92.0   Mumbai
2   Ravi  19.0    NaN     Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0      NaN
```

In [ ]:
data = {
    'Name' : ['Aman', 'Neha', 'Ravi', 'Priya', 'Karan'],
    'Age' : [20, np.nan, 19, 22, 20],
    'Marks' : [85, 92, np.nan, 88, 95],
    'City' : ['Delhi', 'Mumbai', 'Pune', 'Indore', np.nan]
}
df = pd.DataFrame(data)
df

    Name   Age  Marks    City
0   Aman  20.0   85.0   Delhi
1   Neha   NaN   92.0  Mumbai
2   Ravi  19.0    NaN    Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0     NaN

## Q2. Display the first 3 rows.

In [ ]:
df.head(2)

   Name   Age  Marks    City
0  Aman  20.0   85.0   Delhi
1  Neha   NaN   92.0  Mumbai

## Q3. Display the last 2 rows.

In [ ]:
df.tail(2)

    Name   Age  Marks    City
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0     NaN

## Q4. Find the shape of the DataFrame.

In [ ]:
df.shape

(5, 4)

## Q5. Display all column names.

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='object')

## Q6. Display the data types of all columns.

In [ ]:
df.dtypes

Name      object
Age      float64
Marks    float64
City      object
dtype: object

## Q7. Find the total number of missing values in each column using `isnull().sum()`.

Expected Output:
```
Name     0
Age      1
Marks    1
City     1
dtype: int64
```

In [ ]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     1
dtype: int64

## Q8. Fill missing values in the Age column with **21** using `fillna()`.

In [ ]:
df['Age'] = df['Age'].fillna(21)
df['Age']

0    20.0
1    21.0
2    19.0
3    22.0
4    20.0
Name: Age, dtype: float64

## Q9. Fill missing values in the Marks column with the column mean.

In [ ]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df['Marks'].mean())
df

90.0

    Name   Age  Marks    City
0   Aman  20.0   85.0   Delhi
1   Neha  21.0   92.0  Mumbai
2   Ravi  19.0   90.0    Pune
3  Priya  22.0   88.0  Indore
4  Karan  20.0   95.0     NaN

## Q10. Fill missing values in the City column with **Unknown**.

In [ ]:
df['City'] = df['City'].fillna('Unknown')
df

    Name   Age  Marks     City
0   Aman  20.0   85.0    Delhi
1   Neha  21.0   92.0   Mumbai
2   Ravi  19.0   90.0     Pune
3  Priya  22.0   88.0   Indore
4  Karan  20.0   95.0  Unknown

## Q11. Select only the Name and Marks columns.

In [ ]:
df[['Name', 'Marks']]

    Name  Marks
0   Aman   85.0
1   Neha   92.0
2   Ravi   90.0
3  Priya   88.0
4  Karan   95.0

## Q12. Using `loc`, print the first 3 rows.

In [ ]:
df.loc[0:2]

   Name   Age  Marks    City
0  Aman  20.0   85.0   Delhi
1  Neha  21.0   92.0  Mumbai
2  Ravi  19.0   90.0    Pune

## Q13. Using `iloc`, print rows 1 to 3 and columns 0 to 2.

In [ ]:
df.iloc[ 1:4 , 0:3 ]

    Name   Age  Marks
1   Neha  21.0   92.0
2   Ravi  19.0   90.0
3  Priya  22.0   88.0

## Q14. Rename the column Marks to Score.

In [ ]:
df = df.rename(columns={ 'Marks' : 'Score' })
df

    Name   Age  Score     City
0   Aman  20.0   85.0    Delhi
1   Neha  21.0   92.0   Mumbai
2   Ravi  19.0   90.0     Pune
3  Priya  22.0   88.0   Indore
4  Karan  20.0   95.0  Unknown

## Q15. Set Name as the index.

In [ ]:
df = df.set_index('Name')
df

        Age  Score     City
Name
Aman   20.0   85.0    Delhi
Neha   21.0   92.0   Mumbai
Ravi   19.0   90.0     Pune
Priya  22.0   88.0   Indore
Karan  20.0   95.0  Unknown

## Q16. Reset Name as the index.

In [ ]:
df = df.reset_inde