# 🐼 Pandas Assignment (Class 1 & 2)

### Topics Covered
- Importing Pandas
- Series
- DataFrame
- DataFrame Creation
- head(), tail(), info(), describe()
- Column Selection
- loc & iloc
- index, columns, values
- rename()
- set_index()

**Instructions:** Solve every question in the code cell below it.

## Q1. Import the **pandas** library using the alias `pd`.

In [ ]:
# Write your answer here
import pandas as pd

## Q2. Create a **Series** containing: 10, 20, 30, 40, 50.

In [ ]:
# Write your answer here
a = pd.Series([10, 20, 30, 40, 50], name = 'Series', index = ['A', 'B', 'C', 'D', 'E'])
a

A    10
B    20
C    30
D    40
E    50
Name: Series, dtype: int64

## Q3. Create a DataFrame having columns **Name**, **Age**, and **City** with at least 5 records.

In [ ]:
# Write your answer here
data = {
    'Name' : ['Chetan', 'Rohan', 'Ramesh', 'Niraj', 'Piyush'],
    'Age' : [19, 21, 23, 20, 10],
    'City' : ['Nagpur', 'Bhopal', 'Indore', 'Sanchi', 'Delhi']
}
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D', 'E'])
df

     Name  Age    City
A  Chetan   19  Nagpur
B   Rohan   21  Bhopal
C  Ramesh   23  Indore
D   Niraj   20  Sanchi
E  Piyush   10   Delhi

## Q4. Create a DataFrame using a NumPy array of your choice.

In [ ]:
# Write your answer here
import numpy as np

data = np.array([

            ['Chetan', 'Rohan', 'Ramesh', 'Niraj', 'Piyush'],
            [19, 21, 23, 20, 10],
            ['Nagpur', 'Bhopal', 'Indore', 'Sanchi', 'Delhi']

        ])
df = pd.DataFrame(data, index=['Name', 'Age', 'City'])
print(df, '\n')


name = np.array(['Chetan', 'Rohan', 'Ramesh', 'Niraj', 'Piyush'])
age = np.array([19, 21, 23, 20, 10])
city = np.array(['Nagpur', 'Bhopal', 'Indore', 'Sanchi', 'Delhi'])

df = pd.DataFrame({
    'Name' : name,
    'Age' : age,
    'City' : city
})
print(df)

           0       1       2       3       4
Name  Chetan   Rohan  Ramesh   Niraj  Piyush
Age       19      21      23      20      10
City  Nagpur  Bhopal  Indore  Sanchi   Delhi

     Name  Age    City
0  Chetan   19  Nagpur
1   Rohan   21  Bhopal
2  Ramesh   23  Indore
3   Niraj   20  Sanchi
4  Piyush   10   Delhi

## Q5. Display the first **3 rows** of a DataFrame using `head()`.

In [ ]:
# Write your answer here
df.head(3)

     Name  Age    City
0  Chetan   19  Nagpur
1   Rohan   21  Bhopal
2  Ramesh   23  Indore

## Q6. Display the last **2 rows** using `tail()`.

In [ ]:
# Write your answer here
df.tail(2)

     Name  Age    City
3   Niraj   20  Sanchi
4  Piyush   10   Delhi

## Q7. Display the information of a DataFrame using `info()`.

In [ ]:
# Write your answer here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

## Q8. Display the statistical summary using `describe()`.

In [ ]:
# Write your answer here
df.describe()

             Age
count   5.000000
mean   18.600000
std     5.029911
min    10.000000
25%    19.000000
50%    20.000000
75%    21.000000
max    23.000000

## Q9. Select only the **Name** column.

In [ ]:
# Write your answer here
df['Name']

0    Chetan
1     Rohan
2    Ramesh
3     Niraj
4    Piyush
Name: Name, dtype: object

## Q10. Select the **Name** and **Age** columns together.

In [ ]:
# Write your answer here
df[['Name', 'City']]

     Name    City
0  Chetan  Nagpur
1   Rohan  Bhopal
2  Ramesh  Indore
3   Niraj  Sanchi
4  Piyush   Delhi

## Q11. Using `loc`, print the first three rows.

In [ ]:
# Write your answer here
df.loc[0 : 2]

     Name  Age    City
0  Chetan   19  Nagpur
1   Rohan   21  Bhopal
2  Ramesh   23  Indore

## Q12. Using `iloc`, print rows 1 to 3 and the first two columns.

In [ ]:
# Write your answer here
df.iloc[1 : 4,  : 2]

     Name  Age
1   Rohan   21
2  Ramesh   23
3   Niraj   20

## Q13. Print the DataFrame's `index`, `columns`, and `values`.

In [ ]:
# Write your answer here
print(f"Index : {df.index}\n")
print(f"Columns : {df.columns}\n")
print(f"Values : \n{df.values}\n")

Index : RangeIndex(start=0, stop=5, step=1)

Columns : Index(['Name', 'Age', 'City'], dtype='object')

Values :
[['Chetan' 19 'Nagpur']
 ['Rohan' 21 'Bhopal']
 ['Ramesh' 23 'Indore']
 ['Niraj' 20 'Sanchi']
 ['Piyush' 10 'Delhi']]

## Q14. Rename the column **Name** to **Student_Name**.

In [ ]:
# Write your answer here
df = df.rename(columns={'Name' : 'Student_Name'})
df

  Student_Name  Age    City
0       Chetan   19  Nagpur
1        Rohan   21  Bhopal
2       Ramesh   23  Indore
3        Niraj   20  Sanchi
4       Piyush   10   Delhi

## Q15. Set the **Name** column as the index of the DataFrame.

In [ ]:
df = df.set_index("Student_Name")
df

              Age    City
Student_Name
Chetan         19  Nagpur
Rohan          21  Bhopal
Ramesh         23  Indore
Niraj          20  Sanchi
Piyush         10   Delhi

## Q16. **Reset** the **Name** column as the index of the DataFrame.

In [ ]:
df = df.reset_index()
df

  Student_Name  Age    City
0       Chetan   19  Nagpur
1        Rohan   21  Bhopal
2       Ramesh   23  Indore
3        Niraj   20  Sanchi
4       Piyush   10   Delhi